# This is an example for handing over outputs between jobs
# https://docs.github.com/en/github-ae@latest/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idoutputs

name: outputs

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:
    inputs:
      username:
        description: 'A username passed from the caller workflow'
        default: "${github.actor}"
        required: false
        type: string
  # Allows to invoke this workflow from another workflow.
  workflow_call:
    inputs:
      username:
        description: 'A username passed from the caller workflow'
        default: "${github.actor}"
        required: false
        type: string

permissions: {}

jobs:
  init:
    name: "Initialize Environment"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      name: ${{ steps.name.outputs.result }}
    steps:
      - id: name
        name: "Set Name"
        run: |
          echo "result=${{ inputs.username }}" >> $GITHUB_OUTPUT
  hello:
    name: "Say Hello"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs:
      - init
    env:
      NAME: ${{ needs.init.outputs.name }}
    steps:
      - id: main
        name: "Main"
        run: |
          echo "Hello ${{ env.NAME }}!" >> $GITHUB_STEP_SUMMARY
