# This is an example for handing over outputs between jobs
# https://docs.github.com/en/github-ae@latest/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idoutputs

name: outputs

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  init:
    name: "Initialize Environment"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      is_manual: ${{ steps.is_manual.outputs.result }}
      is_draft: ${{ steps.is_draft.outputs.result }}
      is_main: ${{ steps.is_main.outputs.result }}
      is_run: ${{ steps.is_run.outputs.result }}
    steps:
      - id: is_manual
        name: "Action: Manually Triggered?"
        run: |
          [ ${{ github.event_name }} == "workflow_dispatch" ] && result="true" || result="false"
          echo "result=${result}" >> $GITHUB_OUTPUT
      - id: is_draft
        name: "Pull Request: Draft?"
        run: |
          [ ${{ github.event.pull_request.draft }} ] && result="true" || result="false"
          echo "result=${result}" >> $GITHUB_OUTPUT
      - id: is_main
        name: "Main?"
        run: |
          [ ${{ github.ref }} == "refs/heads/main" ] && result="true" || result="false"
          echo "result=${result}" >> $GITHUB_OUTPUT
      - id: is_run
        name: "Run?"
        run: |
          # Allow to run if:
          # - manually triggered
          # - or automatically triggered and neither on main nor triggered for draft pull request.
          [[ ${{ steps.is_manual.outputs.result }} == "true" || (${{ steps.is_main.outputs.result }} == "false" && ${{ steps.is_draft.outputs.result }} == "false") ]] && result="true" || result="false"
          echo "result=${result}" >> $GITHUB_OUTPUT
  on_run:
    name: "Run on Run"
    runs-on: ubuntu-latest
    needs:
      - init
    if: ${{ needs.init.outputs.is_run == 'true' }}
    steps:
      - run: echo "Run!"
  on_norun:
    name: "Run on Not-Run"
    runs-on: ubuntu-latest
    needs:
      - init
    if: ${{ needs.init.outputs.is_run == 'false' }}
    steps:
      - run: echo "Don't Run!"
  on_run_after:
    name: "Run on Run (After)"
    runs-on: ubuntu-latest
    needs:
      - on_run
    steps:
      - run: echo "Done: Run!"
  on_norun_after:
    name: "Run on Not-Run (After)"
    runs-on: ubuntu-latest
    needs:
      - on_norun
    steps:
      - run: echo "Done: Don't Run!"
  report_outputs:
    name: "Report Outputs"
    runs-on: ubuntu-latest
    needs:
      - init
    env:
      IS_MANUAL: ${{ needs.init.outputs.is_manual }}
      IS_DRAFT: ${{ needs.init.outputs.is_draft }}
      IS_MAIN: ${{ needs.init.outputs.is_main }}
      IS_RUN: ${{ needs.init.outputs.is_run }}
    steps:
      - id: report
        name: "Report"
        run: |
          echo "IS_MANUAL: ${IS_MANUAL}"
          echo "IS_DRAFT: ${IS_DRAFT}"
          echo "IS_MAIN: ${IS_MAIN}"
          echo "IS_RUN: ${IS_RUN}"

