# This is an example for handing over outputs between jobs
# https://docs.github.com/en/github-ae@latest/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idoutputs

name: outputs

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:
    inputs:
      username:
        description: |
          Your Name
        default: ""
        required: false
        type: string
  # Allows to invoke this workflow from another workflow.
  workflow_call:
    inputs:
      username:
        description: |
          Your Name
        default: ""
        required: false
        type: string

permissions: {}

jobs:
  vars:
    name: "Set Variables"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - id: name
        name: "Use Default Name?"
        run: |
          username="${{ inputs.username }}"
          result="${username:-${{ github.actor }}}"
          echo "result=${result}" >> $GITHUB_OUTPUT
    outputs:
      name: ${{ steps.name.outputs.result }}
  hello:
    name: "Say Hello"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs:
      - vars
    env:
      NAME: ${{ needs.vars.outputs.name }}
    steps:
      - id: main
        name: "Main"
        run: |
          echo "Hello ${{ env.NAME }}!" >> $GITHUB_STEP_SUMMARY
