# Demonstration how to set secrets from Github Workflows

name: set-secret

on:
  workflow_dispatch:
  workflow_call:

permissions:
  # Write required to write secrets
  # Read required to access secrets (implied by "write")
  # Otherwise, will fail with:
  #
  #     failed to fetch public key: HTTP 403: Resource not accessible by integration (https://api.github.com/repos/mmichaelis/github-actions-sandbox/actions/secrets/public-key)
  #
  # <https://docs.github.com/en/rest/overview/permissions-required-for-github-apps?apiVersion=2022-11-28#repository-permissions-for-secrets>
  actions: write
  # Required for Checkout
  contents: read

# Required token. Otherwise will fail with:
#   gh: To use GitHub CLI in a GitHub Actions workflow, set the GH_TOKEN environment variable.
env:
  GH_TOKEN: ${{ github.token }}

jobs:
  main:
    name: "Set Secret"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      # Checkout required to use `gh`
      - id: checkout
        name: 'Checkout'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: false
      - id: set-token
        name: "Set Secret"
        run: |
          secret="Very secret secret!"
          # Ensure, the secret is not exposed in output.
          echo "::add-mask::${secret}"
          # Propagate Secret
          # Without app specified defaults to: actions, dependabot
          gh auth login
          gh secret set VerySecret --body "${secret}"
